### ISSUE TITLE
Ability to upload any arbitrary CSV for viewing in historical tab

### ISSUE THREAD

**Issue by WillEhman** [UCalgaryRacing/SchulichVelocity#3]
For users, it would be useful if previous data (from previous competitions) could be uploaded for analysis in the same tool. Since this previous data may not have had the same sensors or formatting, it is important to make this tool generic. There may be differences in the headers between DAQ data as well (long vs short headers)

**Comment by WillEhman** [comment]
@arhamHumayun I believe you've already completed this?

**Comment by arhamHumayun** [comment]
Yup, this is all done now. The current system is generic enough to work with any given headers. But it still requires the interval header still since we have to differentiate whats on the x-axis.  I'll leave this open in case there's anything missing.

**Comment by WillEhman** [comment]
If there's any additional small issues they can be identified later.
