### ISSUE TITLE
Suspension data plots

### ISSUE THREAD

**Issue by WillEhman** [UCalgaryRacing/SchulichVelocity#5]
For both historical and streaming data, suspension plots should be generated. 
These will contain accelerations(3 x lines), rotation(3 x lines), AccelX v Accely (Scatterplot), and potentiometer and wheelspeed data

**Comment by WillEhman** [comment]
Accelx/accely
speed as a function of time (especially with lap overlays) (speed can come from an average of wheel speeds or from GPS speed)
Accely as a function of time (especially with lap overlays)
All 4 linear potentiometers as a function of time
4 Wheel speed sensors as a function of time

And ideally these would just be defaults and we would have ways to configure what shows up via dropdown menus/toggles

**Comment by arhamHumayun** [comment]
All of these are done except 4 wheel speed sensors as it isn't on the csv. Adding it should be simple so I'm closing this issue.
