### ISSUE TITLE
Powertrain Data Plots

### ISSUE THREAD

**Issue by WillEhman** [UCalgaryRacing/SchulichVelocity#6]
For both streaming and historical data, plots of temperatures(line plots), rpm, map, afr, and associate dpowertrain plots will need to be generated

**Comment by WillEhman** [comment]
All temps as a function of time
All pressures as a function of time (MAP,oil)
AFR/time
speed as a function of time (especially with lap overlays) (speed can come from an average of wheel speeds or from GPS speed)
Rpm and speed/time
Gear/time (ideally on same graph as rpm and speed)

And ideally these would just be defaults and we would have ways to configure what shows up via dropdown menus/toggles

**Comment by arhamHumayun** [comment]
All of these are done except gear/time since it isn't on the CSV. Adding it should be very simple so I'm closing this issue.
