### ISSUE TITLE
Figure out how to make graphs

### ISSUE THREAD

**Issue by WillEhman** [UCalgaryRacing/SchulichVelocity#9]
Graph.js or D3js. Figure out what works and understand it

**Comment by arhamHumayun** [comment]
Figured out how to update graph with new static data. Have working example. 

Also figured out how to update graph with new points, but run into bug where graph doesn't re-render itself after a new plot is added. Have semi-working example.
May use D3js and not Chartjs for dynamic graphs.

We have to create a function that maps all points onto two separate arrays, one for labels, and one for data.

**Comment by WillEhman** [comment]
This is complete. add note and close @arhamHumayun

**Comment by arhamHumayun** [comment]
Have gotten good grasp of how to make charts with chartjs. It does everything we need it to do such as make line charts, scatter charts, stream, and refresh with new data.
